# Generated by Django 3.2.24 on 2024-03-21 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_rename_booking_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
