# Generated by Django 3.2.24 on 2024-03-07 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name_plural': 'Home Page'},
        ),
    ]
