# Generated by Django 3.2.24 on 2024-03-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_category_menuitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeverageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Beverage Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='menuitems',
            options={'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurant.category'),
        ),
        migrations.CreateModel(
            name='BeverageItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('beverage_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beverage_items', to='restaurant.beveragecategory')),
            ],
            options={
                'verbose_name_plural': 'Beverage Items',
            },
        ),
    ]
